import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { z } from "zod";

const appointmentSchema = z.object({
  full_name: z.string().trim().min(1, "Full name is required").max(100),
  email: z.string().trim().email("Invalid email address").max(255),
  phone: z.string().trim().min(1, "Phone number is required").max(20),
  appointment_date: z.string().min(1, "Preferred date is required"),
  appointment_time: z.string().min(1, "Preferred time is required"),
  meeting_type: z.string().optional(),
  notes: z.string().max(1000).optional(),
});

const timeSlots = [
  "9:00 AM",
  "10:00 AM",
  "11:00 AM",
  "1:00 PM",
  "2:00 PM",
  "3:00 PM",
  "4:00 PM",
];

const AppointmentForm = () => {
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [formData, setFormData] = useState({
    full_name: "",
    email: "",
    phone: "",
    appointment_date: "",
    appointment_time: "",
    meeting_type: "office_visit",
    notes: "",
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    setErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setErrors({});

    try {
      const validated = appointmentSchema.parse(formData);

      const { error } = await supabase.from("appointments").insert({
        full_name: validated.full_name,
        email: validated.email,
        phone: validated.phone,
        appointment_date: validated.appointment_date,
        appointment_time: validated.appointment_time,
        meeting_type: validated.meeting_type || null,
        notes: validated.notes || null,
        reference_number: "", // Will be auto-generated by trigger
      });

      if (error) throw error;

      setSubmitted(true);
      toast({
        title: "Appointment Booked!",
        description: "Thank you! We'll confirm your appointment within 24 hours.",
      });
    } catch (error: unknown) {
      if (error instanceof z.ZodError) {
        const fieldErrors: Record<string, string> = {};
        error.errors.forEach((err) => {
          if (err.path[0]) {
            fieldErrors[err.path[0] as string] = err.message;
          }
        });
        setErrors(fieldErrors);
      } else {
        toast({
          title: "Error",
          description: "Something went wrong. Please try again.",
          variant: "destructive",
        });
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  // Get minimum date (tomorrow)
  const getMinDate = () => {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    return tomorrow.toISOString().split("T")[0];
  };

  if (submitted) {
    return (
      <div className="text-center py-8">
        <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
          <svg
            className="w-8 h-8 text-primary"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M5 13l4 4L19 7"
            />
          </svg>
        </div>
        <h3 className="font-display text-2xl font-semibold mb-2">
          Appointment Requested!
        </h3>
        <p className="text-gray-text">
          We'll confirm your appointment within 24 hours. Check your email for updates.
        </p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium mb-2">
            Full Name <span className="text-destructive">*</span>
          </label>
          <input
            type="text"
            name="full_name"
            value={formData.full_name}
            onChange={handleChange}
            className="form-input"
            placeholder="Juan Dela Cruz"
            required
          />
          {errors.full_name && (
            <p className="text-destructive text-sm mt-1">{errors.full_name}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">
            Email Address <span className="text-destructive">*</span>
          </label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            className="form-input"
            placeholder="juan@email.com"
            required
          />
          {errors.email && (
            <p className="text-destructive text-sm mt-1">{errors.email}</p>
          )}
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium mb-2">
          Phone Number <span className="text-destructive">*</span>
        </label>
        <input
          type="tel"
          name="phone"
          value={formData.phone}
          onChange={handleChange}
          className="form-input"
          placeholder="0917 123 4567"
          required
        />
        {errors.phone && (
          <p className="text-destructive text-sm mt-1">{errors.phone}</p>
        )}
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium mb-2">
            Preferred Date <span className="text-destructive">*</span>
          </label>
          <input
            type="date"
            name="appointment_date"
            value={formData.appointment_date}
            onChange={handleChange}
            className="form-input"
            min={getMinDate()}
            required
          />
          {errors.appointment_date && (
            <p className="text-destructive text-sm mt-1">{errors.appointment_date}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">
            Preferred Time <span className="text-destructive">*</span>
          </label>
          <select
            name="appointment_time"
            value={formData.appointment_time}
            onChange={handleChange}
            className="form-input"
            required
          >
            <option value="">Select time</option>
            {timeSlots.map((time) => (
              <option key={time} value={time}>
                {time}
              </option>
            ))}
          </select>
          {errors.appointment_time && (
            <p className="text-destructive text-sm mt-1">{errors.appointment_time}</p>
          )}
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium mb-3">
          Meeting Type <span className="text-destructive">*</span>
        </label>
        <div className="flex flex-wrap gap-4">
          {[
            { value: "office_visit", label: "Office Visit" },
            { value: "video_call", label: "Video Call" },
            { value: "phone_call", label: "Phone Call" },
          ].map((option) => (
            <label key={option.value} className="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name="meeting_type"
                value={option.value}
                checked={formData.meeting_type === option.value}
                onChange={handleChange}
                className="w-4 h-4 text-primary border-border focus:ring-primary"
              />
              <span className="text-sm">{option.label}</span>
            </label>
          ))}
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium mb-2">
          Additional Notes (Optional)
        </label>
        <textarea
          name="notes"
          value={formData.notes}
          onChange={handleChange}
          className="form-textarea"
          rows={3}
          placeholder="Any specific topics you'd like to discuss..."
        />
      </div>

      <Button
        type="submit"
        variant="default"
        className="w-full rounded-full"
        disabled={isSubmitting}
      >
        {isSubmitting ? "Booking..." : "Book Appointment"}
      </Button>
    </form>
  );
};

export default AppointmentForm;
