import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { z } from "zod";

const inquirySchema = z.object({
  full_name: z.string().trim().min(1, "Full name is required").max(100),
  email: z.string().trim().email("Invalid email address").max(255),
  phone: z.string().trim().min(1, "Phone number is required").max(20),
  event_type: z.string().optional(),
  event_date: z.string().optional(),
  guest_count: z.number().optional(),
  package_interested: z.string().optional(),
  message: z.string().max(2000).optional(),
});

const InquiryForm = () => {
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [formData, setFormData] = useState({
    full_name: "",
    email: "",
    phone: "",
    event_type: "",
    event_date: "",
    guest_count: "",
    package_interested: "",
    message: "",
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    setErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setErrors({});

    try {
      const dataToValidate = {
        ...formData,
        guest_count: formData.guest_count ? parseInt(formData.guest_count) : undefined,
      };

      const validated = inquirySchema.parse(dataToValidate);

      const { error } = await supabase.from("inquiries").insert({
        full_name: validated.full_name,
        email: validated.email,
        phone: validated.phone,
        event_type: validated.event_type || null,
        event_date: validated.event_date || null,
        guest_count: validated.guest_count || null,
        package_interested: validated.package_interested || null,
        message: validated.message || null,
        reference_number: "", // Will be auto-generated by trigger
      });

      if (error) throw error;

      setSubmitted(true);
      toast({
        title: "Inquiry Sent!",
        description: "Thank you! We'll contact you within 24 hours.",
      });
    } catch (error: unknown) {
      if (error instanceof z.ZodError) {
        const fieldErrors: Record<string, string> = {};
        error.errors.forEach((err) => {
          if (err.path[0]) {
            fieldErrors[err.path[0] as string] = err.message;
          }
        });
        setErrors(fieldErrors);
      } else {
        toast({
          title: "Error",
          description: "Something went wrong. Please try again.",
          variant: "destructive",
        });
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  if (submitted) {
    return (
      <div className="text-center py-8">
        <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
          <svg
            className="w-8 h-8 text-primary"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M5 13l4 4L19 7"
            />
          </svg>
        </div>
        <h3 className="font-display text-2xl font-semibold mb-2">Thank You!</h3>
        <p className="text-gray-text">
          We've received your inquiry and will contact you within 24 hours.
        </p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium mb-2">
            Full Name <span className="text-destructive">*</span>
          </label>
          <input
            type="text"
            name="full_name"
            value={formData.full_name}
            onChange={handleChange}
            className="form-input"
            placeholder="Juan Dela Cruz"
            required
          />
          {errors.full_name && (
            <p className="text-destructive text-sm mt-1">{errors.full_name}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">
            Email Address <span className="text-destructive">*</span>
          </label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            className="form-input"
            placeholder="juan@email.com"
            required
          />
          {errors.email && (
            <p className="text-destructive text-sm mt-1">{errors.email}</p>
          )}
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium mb-2">
            Phone Number <span className="text-destructive">*</span>
          </label>
          <input
            type="tel"
            name="phone"
            value={formData.phone}
            onChange={handleChange}
            className="form-input"
            placeholder="0917 123 4567"
            required
          />
          {errors.phone && (
            <p className="text-destructive text-sm mt-1">{errors.phone}</p>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">Event Type</label>
          <select
            name="event_type"
            value={formData.event_type}
            onChange={handleChange}
            className="form-input"
          >
            <option value="">Select event type</option>
            <option value="Wedding">Wedding</option>
            <option value="Debut">Debut</option>
            <option value="Birthday">Birthday</option>
            <option value="Corporate">Corporate</option>
            <option value="Other">Other</option>
          </select>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium mb-2">
            Estimated Event Date
          </label>
          <input
            type="date"
            name="event_date"
            value={formData.event_date}
            onChange={handleChange}
            className="form-input"
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">
            Estimated Number of Guests
          </label>
          <input
            type="number"
            name="guest_count"
            value={formData.guest_count}
            onChange={handleChange}
            className="form-input"
            placeholder="100"
            min="1"
          />
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium mb-2">
          Package Interested In
        </label>
        <select
          name="package_interested"
          value={formData.package_interested}
          onChange={handleChange}
          className="form-input"
        >
          <option value="">Select a package</option>
          <option value="250K All-In">250K All-In Package</option>
          <option value="Intimate">Intimate Package</option>
          <option value="Premium">Premium Package</option>
          <option value="Debut">Debut Package</option>
          <option value="Custom">Custom Package</option>
        </select>
      </div>

      <div>
        <label className="block text-sm font-medium mb-2">
          Message / Questions
        </label>
        <textarea
          name="message"
          value={formData.message}
          onChange={handleChange}
          className="form-textarea"
          rows={4}
          placeholder="Tell us more about your event..."
        />
      </div>

      <Button
        type="submit"
        variant="default"
        className="w-full rounded-full"
        disabled={isSubmitting}
      >
        {isSubmitting ? "Sending..." : "Send Inquiry"}
      </Button>
    </form>
  );
};

export default InquiryForm;
